# < https://docs.travis-ci.com/user/integration/platformio/ >
# < http://docs.platformio.org/page/ci/travis.html >
# < http://docs.platformio.org/page/userguide/cmd_ci.html >

language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

script:
  - platformio run
